engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 200
  eslint:
    enabled: true
    exclude_paths:
    - "**/*"
    - "!utils/timesheets.js"
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "lib/**"
- "test/**"
- "example/**"
- "LICENSE"
- "README.md"
- "config.json"
- "package.json"
- "generators/**/templates"
