languages:
  JavaScript: true

engines:
  eslint:
    enabled: false

exclude_paths:
- "lib/**"
- "test/**"
- "example/**"
- "LICENSE"
- "README.md"
- "config.json"
- "package.json"
- "generators/**/templates"
